### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by jsousou77** [Elite4r/eaglerRelay#1]
Idk if anyone is looking at this repo anymore but I tried to run my own instance and it doesn't seem to work for EaglercraftX 1.8 u29. If I host a shared world, it shows up on the multiplayer list, but if I try to join it, it says "Failed to connect to 3altb!" It logs in the console `[LANClientNetworkManager]: Relay [ws://<IP>:8081|3altb] client provide ICE candidate timeout` on the tab I'm trying to join from, and `[IntegratedServerLAN]: Relay [ws://<IP>:8081] unexpected packet: IPacketFEDisconnectClient` on the tab that's hosting the world.

**Comment by jsousou77** [comment]
It does the same thing on eaglercraft 1.5.2 as well

**Comment by Elite4r** [comment]
> Idk if anyone is looking at this repo anymore but I tried to run my own instance and it doesn't seem to work for EaglercraftX 1.8 u29. If I host a shared world, it shows up on the multiplayer list, but if I try to join it, it says "Failed to connect to 3altb!" It logs in the console `[LANClientNetworkManager]: Relay [ws://<IP>:8081|3altb] client provide ICE candidate timeout` on the tab I'm trying to join from, and `[IntegratedServerLAN]: Relay [ws://<IP>:8081] unexpected packet: IPacketFEDisconnectClient` on the tab that's hosting the world.

I will try to work on this.

**Comment by jsousou77** [comment]
Never mind, I think this was caused by an outdated chrome version. It seems to be fixed now

**Comment by Elite4r** [comment]
Thank you, I realized that it didn't work either, and it was because of a slow IDE
